apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: discovery
  name: discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery
  template:
    metadata:
      labels:
        app: discovery
    spec:
      containers:
        - image: guill392/discovery-service:latest
          name: discovery
          ports:
            - containerPort: 8761
      restartPolicy: Always