apiVersion: v1
kind: Service
metadata:
  name: discovery-service
spec:
  selector:
      name: discovery
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      nodePort: 30000