apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-server
  labels:
    app: store-server 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-server
  template:
    metadata:
      labels:
        app: store-server
    spec:
      containers:
        - name: store-server
          image: guill392/store-service:latest
          env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://discovery-server-service:8761/eureka
            - name: SPRING_APPLICATION_NAME
              value: STORE-SERVICE
          ports:
            - containerPort: 7000
      restartPolicy: Always